name: Build dockerimage and package helmchart, push to ECR

on:
  push:
    branches:
      - "stable"
      - "main"
    tags:
      - "*.*.*"
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0
      - name: Set current epoch time as env variable
        run: echo "NOW=$(date +%s)" >> $GITHUB_ENV
      - name: Echo current date
        run: echo $NOW
      - name: Install chart museum push extension
        run: helm plugin install https://github.com/chartmuseum/helm-push.git
      - name: Bump up chart version
        run: |
          helm release chart --skip-application-version
          cat chart/Chart.yaml
      - name: package helm chart
        run: |
          helm package chart
          export chartVersion=$(helm release chart --print-computed-version)
          export helmpackage=${{ github.event.repository.name }}-$chartVersion
      - name: push helm package
        env:
          CHARTMUSEUM_URL: ${{ secrets.CHARTMUSEUM_URL }}
          CHARTMUSEUM_USER: ${{ secrets.CHARTMUSEUM_USER }}
          CHARTMUSEUM_PASSWORD: ${{ secrets.CHARTMUSEUM_PASSWORD }}
        run: |
          helm cm-push chart $CHARTMUSEUM_URL -u $CHARTMUSEUM_USER -p $CHARTMUSEUM_PASSWORD
