name: Cloud Defense HelmChart Scan

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0
      - name: Generate template
        run: |
          mkdir /tmp/charts
          helm template chart/ > /tmp/charts/$GITHUB_SHA.yaml
      - name: Install Cloud Defense
        run: |
          curl https://raw.githubusercontent.com/CloudDefenseAI/cd/master/latest/cd-latest-linux-x64.tar.gz > /tmp/cd-latest-linux-x64.tar.gz
          tar -C /tmp -xzf /tmp/cd-latest-linux-x64.tar.gz
          chmod +x /tmp/cdefense
      - name: Run Cloud Defense Scan
        run: /tmp/cdefense kubernetes --api-key=${{ secrets.CLOUDDEFENSE_API_TOKEN }} --project-name=$GITHUB_REPOSITORY  --path=/tmp/charts
