name: Cloud Defense Node.js

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with: 
          node-version: "12"
      - name: Install deps
        run: npm install && npm install -g license-checker
      - name: Install Cloud Defense
        run: |
          curl https://raw.githubusercontent.com/CloudDefenseAI/cd/master/latest/cd-latest-linux-x64.tar.gz > /tmp/cd-latest-linux-x64.tar.gz
          tar -C /tmp -xzf /tmp/cd-latest-linux-x64.tar.gz
          chmod +x /tmp/cdefense
      - name: Run Cloud Defense Scan
        run: /tmp/cdefense scan --lang=node --project-name=$GITHUB_REPOSITORY --api-key=${{ secrets.CLOUDDEFENSE_API_TOKEN }} --path=$PWD

