name: Cloud Defense golang

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.15.x, 1.16.x]
    env:
       HYPERDRIVE_REGISTRY_TOKEN: ${{ secrets.HYPERDRIVE_REGISTRY_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: set up golang ${{ matrix.go-version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Install Cloud Defense
        run: |
          curl https://raw.githubusercontent.com/CloudDefenseAI/cd/master/latest/cd-latest-linux-x64.tar.gz > /tmp/cd-latest-linux-x64.tar.gz
          tar -C /tmp -xzf /tmp/cd-latest-linux-x64.tar.gz
          chmod +x /tmp/cdefense
      - name: Run Cloud Defense Scan
        run: /tmp/cdefense scan --lang=go --project-name=$GITHUB_REPOSITORY --api-key=${{ secrets.CLOUDDEFENSE_API_TOKEN }} --path=$PWD
