name: "Docker Build and Push"
env:
  REGISTRY: ghcr.io

on:
  push:
    branches:
      - "stable"
    paths:
      - "Dockerfile"
  pull_request:
    branches:
      - "stable"
  schedule:
    # Weekly, at 03:00 on Monday UTC time
    - cron: "0 3 * * 1"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      -
        name: Set current epoch time as env variable
        run: echo "NOW=$(date +%s)" >> $GITHUB_ENV

      -
        name: Echo current date
        run: echo $NOW

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      -
        name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      -
        name: Login to Docker registry
        uses: docker/login-action@v1
        if: github.event_name != 'pull_request'
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      -
        name: Docker meta
        id: meta
        uses: crazy-max/ghaction-docker-meta@v2
        with:
          images: ghcr.io/${{ github.repository }}
          labels: |
            maintainer=
            org.opencontainers.image.title=
            org.opencontainers.image.description=
            org.opencontainers.image.vendor=Hypergiant, LLC.
            org.opencontainers.image.source=${{github.server_url}}/${{github.repository}}
          tags: |
            type=edge
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix=sha-,suffix=-${{env.NOW}},format=short
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - 
        name: Build Image
        id: docker-build
        uses: docker/build-push-action@v2
        env:
          DOCKER_BUILDKIT: 1
        with:
          context: .
          file: Dockerfile
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: $ {{ steps.meta.outputs.labels }}
 
      - 
        name: Scan image
        uses: anchore/scan-action@v3
        id: scan
        with:
          image: ghcr.io/${{ github.repository }}/edge
          fail-build: true
          severity-cutoff: high
          acs-report-enable: true

      -
        name: Upload scan report
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}

      -
        name: Inspect SARIF report
        run: cat ${{ steps.scan.outputs.sarif }}
