name: "Build Docker Image"

on:
  pull_request:
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Docker Image
        env:
          DOCKER_FILENAME: ui.Dockerfile
        uses: docker/build-push-action@v2
        with:
            context: .
            file: docker/${{ env.DOCKER_FILENAME }}
            tags: latest
