name: Hypergiant Golang CI workflow

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on

    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2

      - 
        name: Secret Scan
        uses: gohypergiant/secret-scan@04dbad7694a0b9582cb6864f98349f728582d7ea

      -
        name: gosec
        uses: securego/gosec@master
        with:
          args: ./...

