name: Hypergiant Golang CI workflow

on:
  push:

jobs:
  secret-scan:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2

      -
        name: Secret Scan
        uses: gohypergiant/secret-scan@master

  gosec:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2

      -
        name: Setup Go environment
        uses: actions/setup-go@v2.2.0

      -
        name: gosec
        uses: securego/gosec@v2.9.6
        with:
          args: ./...

  lint:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2

      -
        name: Setup Go environment
        uses: actions/setup-go@v2.2.0

      -
        name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          version: v1.29
          skip-go-installation: true
          skip-pkg-cache: false
          skip-build-cache: false

  test:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2

      -
        name: Setup Go environment
        uses: actions/setup-go@v2.2.0

      -
        name: Run unit tests
        run: go test  ./...
