name: Running nodejs Code Coverage with CodeCov

on: [push, pull_request]

jobs:
  run-tests:
    env:
      NODE_ENV: test
      HYPERDRIVE_REGISTRY_TOKEN: ${{ secrets.HYPERDRIVE_REGISTRY_TOKEN }}
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: hyperdrive_credential_management
      POSTGRES_TEST_DB: hyperdrive_credential_management
      POSTGRES_HOST: 127.0.0.1
      POSTGRES_PORT: 5432
      OIDC_CLIENT_ID: foo
      OIDC_SECRET: bar
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: hyperdrive_credential_management
          POSTGRES_PORT: 5432
        ports:
          - "5432:5432"
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 2 

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Run the tests
      run: npm test -- -u --coverage

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
