name: Hypergiant Python CI workflow

on:
  push:
    branches-ignore: [stable, master, main]

jobs:
  secret-scan:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2

      -
        name: Secret Scan
        uses: gohypergiant/secret-scan@master

  lint:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2

      - 
        name: Lint Code Base
        uses: github/super-linter/slim@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: stable
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  security-scan:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2

      -
        name: Setup Python Environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: PyCharm Security Scanner
        uses: tonybaloney/pycharm-security@1.25.1
