name: Go test

on:
  workflow_call:
    inputs:
      go-version:
        required: true
        type: string
      args:
        required: false
        type: string
        default: "./..."
       

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2

      -
        name: Setup Go environment
        uses: actions/setup-go@v2.2.0
        with:
          go-version: ${{inputs.go-version}}

      -
        name: Run unit tests
        run: go test  ${{inputs.args}}
