name: Secret Scan

on:
  workflow_call:

jobs:
  secret-scan:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2

      -
        name: Secret Scan
        uses: gohypergiant/secret-scan@master
