name: Secret Scan

on:
  workflow_call:
    inputs:
      exclude_path:
        required: false
        default: ''
        type: string
      include_path:
        required: false
        default: ''
        type: string

jobs:
  secret-scan:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2

      -
        name: Secret Scan
        uses: gohypergiant/secret-scan@master
        with:
          include_path: ${{ inputs.include_path }}
          exclude_path: ${{ inputs.exclude_path }}
