name: Secret Scan

on:
  workflow_call:

jobs:
  secret-scan:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    inputs:
      exclude_path:
        required: false
        default: ''
      include_path:
        required: false
        default: ''

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2

      -
        name: Secret Scan
        uses: gohypergiant/secret-scan@master
        with:
          include_path: ${{ inputs.include_path }}
          exclude_path: ${{ inputs.exclude_path }}
