name: Super Linter

on:
  workflow_call:
    inputs:
      validate_all_codebase:
        required: false
        type: boolean
        default: false
      default_branch:
        required: false
        type: string
        default: stable


jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2

      - 
        name: Lint Code Base
        uses: github/super-linter/slim@v4
        env:
          VALIDATE_ALL_CODEBASE: ${{ inputs.validate_all_codebase }}
          DEFAULT_BRANCH: ${{ inputs.default_branch }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

